export const departamentosYMunicipios: { [key: string]: string[] } = {
  Amazonas: ['Leticia', 'Puerto Nariño'],
  Antioquia: [
    'Medellín',
    'Envigado',
    'Bello',
    'Itagüí',
    'Rionegro',
    'Turbo',
    'Apartadó',
    'Necoclí',
    'Caucasia',
    'El Bagre',
    'Santa Fe de Antioquia',
    'Girardota',
    'Copacabana',
    'La Ceja',
    'Sabaneta',
    'Marinilla',
  ],
  Arauca: ['Arauca', 'Arauquita', 'Saravena', 'Tame', 'Fortul', 'Cravo Norte'],
  Atlántico: [
    'Barranquilla',
    'Soledad',
    'Malambo',
    'Sabanalarga',
    'Puerto Colombia',
    'Galapa',
    'Baranoa',
    'Polonuevo',
    'Piojó',
  ],
  Bolívar: [
    'Cartagena',
    'Magangué',
    'Turbaco',
    'Arjona',
    'San Juan Nepomuceno',
    'El Carmen de Bolívar',
    'Santa Catalina',
    'Villanueva',
  ],
  Boyacá: [
    'Tunja',
    'Duitama',
    'Sogamoso',
    'Chiquinquirá',
    'Moniquirá',
    'Paipa',
    'Villa de Leyva',
    'Garagoa',
    'Guateque',
    'Soatá',
  ],
  Bogotá: [
    'Bogotá',
  ],
  Caldas: [
    'Manizales',
    'Chinchiná',
    'Villamaría',
    'Anserma',
    'Riosucio',
    'La Dorada',
    'Salamina',
    'Pensilvania',
  ],
  Caquetá: [
    'Florencia',
    'San Vicente del Caguán',
    'Puerto Rico',
    'El Doncello',
    'Morelia',
    'Solano',
    'Solita',
    'Milán',
  ],
  Casanare: [
    'Yopal',
    'Aguazul',
    'Villanueva',
    'Tauramena',
    'Monterrey',
    'Maní',
    'Trinidad',
    'San Luis de Palenque',
  ],
  Cauca: [
    'Popayán',
    'Santander de Quilichao',
    'Puerto Tejada',
    'Caldono',
    'Piendamó',
    'Silvia',
    'Guapi',
    'Inzá',
  ],
  Cesar: [
    'Valledupar',
    'Aguachica',
    'Bosconia',
    'El Copey',
    'Curumaní',
    'Chimichagua',
    'San Diego',
    'Pueblo Bello',
  ],
  Chocó: [
    'Quibdó',
    'Istmina',
    'Condoto',
    'Riosucio',
    'Tadó',
    'Acandí',
    'Nuquí',
    'Bahía Solano',
  ],
  Córdoba: [
    'Montería',
    'Lorica',
    'Sahagún',
    'Cereté',
    'Planeta Rica',
    'Montelíbano',
    'Ciénaga de Oro',
    'Chinú',
  ],
  Cundinamarca: [
    'Bogotá',
    'Soacha',
    'Zipaquirá',
    'Chía',
    'Facatativá',
    'Fusagasugá',
    'Girardot',
    'Cajicá',
  ],
  Guainía: ['Inírida'],
  Guaviare: ['San José del Guaviare', 'El Retorno', 'Calamar', 'Miraflores'],
  Huila: [
    'Neiva',
    'Pitalito',
    'Garzón',
    'La Plata',
    'Campoalegre',
    'San Agustín',
    'Acevedo',
    'Algeciras',
  ],
  'La Guajira': [
    'Riohacha',
    'Maicao',
    'Uribia',
    'San Juan del Cesar',
    'Fonseca',
    'Manaure',
    'Hatonuevo',
    'Dibulla',
  ],
  Magdalena: [
    'Santa Marta',
    'Ciénaga',
    'Plato',
    'El Banco',
    'Fundación',
    'Aracataca',
    'Pivijay',
    'Tenerife',
  ],
  Meta: [
    'Villavicencio',
    'Acacías',
    'Granada',
    'Puerto López',
    'San Martín',
    'Vista Hermosa',
    'Guamal',
    'Mapiripán',
  ],
  Nariño: [
    'Pasto',
    'Tumaco',
    'Ipiales',
    'Túquerres',
    'La Unión',
    'Sandoná',
    'El Tablón de Gómez',
    'La Cruz',
  ],
  'Norte de Santander': [
    'Cúcuta',
    'Ocaña',
    'Pamplona',
    'Villa del Rosario',
    'Los Patios',
    'Tibú',
    'Chinácota',
    'Toledo',
  ],
  Putumayo: [
    'Mocoa',
    'Puerto Asís',
    'Orito',
    'Sibundoy',
    'San Francisco',
    'Colón',
    'Puerto Guzmán',
    'Puerto Leguízamo',
  ],
  Quindío: [
    'Armenia',
    'Calarcá',
    'La Tebaida',
    'Montenegro',
    'Quimbaya',
    'Salento',
    'Circasia',
    'Filandia',
  ],
  Risaralda: [
    'Pereira',
    'Dosquebradas',
    'Santa Rosa de Cabal',
    'Marsella',
    'Belén de Umbría',
    'Quinchía',
    'Apía',
    'Mistrató',
  ],
  'San Andrés y Providencia': ['San Andrés', 'Providencia'],
  Santander: [
    'Bucaramanga',
    'Floridablanca',
    'Girón',
    'Barrancabermeja',
    'Piedecuesta',
    'San Gil',
    'Socorro',
    'Zapatoca',
  ],
  Sucre: [
    'Sincelejo',
    'Corozal',
    'Sampués',
    'Tolú',
    'San Marcos',
    'San Onofre',
    'Galeras',
    'Sincé',
  ],
  Tolima: [
    'Ibagué',
    'Espinal',
    'Melgar',
    'Honda',
    'Líbano',
    'Chaparral',
    'Guamo',
    'Mariquita',
  ],
  'Valle del Cauca': [
    'Cali',
    'Palmira',
    'Buenaventura',
    'Tuluá',
    'Cartago',
    'Buga',
    'Jamundí',
    'Yumbo',
  ],
  Vaupés: ['Mitú'],
  Vichada: ['Puerto Carreño', 'La Primavera', 'Cumaribo', 'Santa Rosalía'],
};
